### ISSUE TITLE
Guild Bank Alts Support

### ISSUE THREAD

**Issue by orionshock** [Jaliborc/Bagnon#1307]
Would be great if the tooltip showed if the same item was also in guild bank of both current and other guilds.

I have a guild bank alt and would also like to see if items are there when on my main that is naturally in a different guild.

Also would be nice if it could show the contents of the guild bank when not at the guild bank and other guilds other chars are part of, see above.

**Comment by Pixolsc2** [comment]
It's calling GetNumGuildBankTabs() of the current character instead of having stored the number of tabs of your alt's guild bank and using that. So if the character that you're logged onto does not have any guild bank tabs purchased, it will think that your alt's guild bank also has zero guild bank tabs. I only ran into this issue because my main's guild had not bought any guild tabs yet.

Solution: Simplest fix is to hard-code 6 guild tabs (6 for TBC-Classic?) into the for loop.
```
AddOns\Bagnon\common\Wildpants\features\tooltipCounts.lua
```

Change:
```
			elseif Addon.sets.countGuild then
				local guild = 0
				for i = 1, GetNumGuildBankTabs() do
					guild = guild + FindItemCount(owner, i, itemID)
				end
```

to:
```
			elseif Addon.sets.countGuild then
				local guild = 0
				for i = 1, 6 do
					guild = guild + FindItemCount(owner, i, itemID)
				end
```

Also don't forget to go into "Esc" > "Interface" > "Addons" > "Bagnon" > Checkmark "Tooltip Item Count" > Checkmark "Include Guild Banks"

**Comment by orionshock** [comment]
> Also don't forget to go into "Esc" > "Interface" > "Addons" > "Bagnon" > Checkmark "Tooltip Item Count" > Checkmark "Include Guild Banks"

Ah; that did the trick :) not sure if that was new or i just overlooked it.
