### ISSUE TITLE
Tooltip Item Count does not display anymore even though the feature is toggled in the addon settings

### ISSUE THREAD

**Issue by Nelythia** [Jaliborc/Bagnon#1473]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3
 - Server patch: 10.0.0

 **Have you read the changelog? (please don't waste our time)**
No

**Describe the bug**
Hovering over the items in your inventory doesn't display the "In Bags: (amount)" tooltip information anymore, even though the option is checked in the addon settings.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Inventory
2. Hover mouse over any item in your inventory, while "Tooltip Item Count" is enabled in the Bagnon addon settings
3. See that it doesn't display the information even though the feature is enabled

**Expected behaviour**
It should display the item amount on character(s) properly

**Screenshots**
https://i.imgur.com/idhtrPR.png

**Error Logs**
None

**Additional context**
None

**Comment by Galthariel** [comment]
I have that same issue with Bagno buil in option to show Item Count however since I have TSM which has the same ability I prefer to use it instead. What is happening is that Bagnon is interfering with the count regardless. It's showing 350 of an item which in reality I have only 200 and I noticed the wrong count happens with all the items in the Reagent Bank. To fix it I need to Disable Bagnon Bank Frame, open the Bank using the Blizz Frame, reenable Bagnon Bank and then it will show the right item count meaning that it's indeed a Bagnon issue.
