### ISSUE TITLE
New Bagnon Update

### ISSUE THREAD

**Issue by webbj8150** [Jaliborc/Bagnon#1536]
Been in the game for several hours and just updated Bagnon. It no longer works. No error message. The bags no longer open.

**Comment by Marcoderm** [comment]
I've been having the same issue. Bagnon hasnt been working since the DF platch. I tried deleting other addons, deleting my wtf folder and still didn't work with zero addons installed. 
thanks,

**Comment by GrammyLove** [comment]
Ive also been having this issue since the 2 pre patchs.   I keep getting message in CHAT in red stating Bagnon has been 
AUTO-DISABLED  .   Ive actually uninstalled WOW and reinstalled it and the Bagnon addons  and still get the same message.   It appears to be the ONLY addon that WOW has decided to auto-disable.   Any suggestions on what I need to do please.   Sad to say but without my bagnon addons I feel like im playing half a game.   Thank you for all your hard work on this app,  it is MUCH appriciated

**Comment by Jevnaker** [comment]
yeah also my wow crashes if i activated the bagnon addon  while i had the one bag blizzard setting.

**Comment by gsnehme92** [comment]
Enable BagBrother Dependency, apparently, they have a shared engine that requires it to be enabled.

**Comment by GrammyLove** [comment]
Im having brain fog right now  gsnehme92 ,  How do I do that?     Sorry I caught covid yesterday from helping mom in hospital all last week and was really looking forward to playing WOW to keep my mind off of feeling crapy haha  .   IF you can instruct how to enable BagBrother  Thx

**Comment by nashutal** [comment]
@GrammyLove Enable it like you would any other addon. Just click the box next to it on the addon panel.

**Comment by Marcoderm** [comment]
Hope it works for you. I have it enabled and no luck for me

**Comment by GrammyLove** [comment]
I had BagBrother enabled and for some reason it disabled it.  SO before logging in the Char, I made sure it was enabled.  Logged in and still didnt work.    Nothing under games Option / addons tab and Bagnon was not there.   I typed  /bgn and it gave me list of commands so   i typed    /bgn config and it POPPED up the options screen with Bagnon NOW on the list at the very bottom......BUT i click on Automatic Display or Frame Settings and BOTH are blank.  The Color settings shows top 2 lines of text telling what it does but nothing under that.............ONLY thing that has content is the Patrons tab......    ANY idea how I can get this to allow me to add my options?   Thanks so far for your help

**Comment by Jaliborc** [comment]
enable lua errors, instal a current version, etc

**Comment by GrammyLove** [comment]
Thank you for your response .   I see you closed it.   I might not be as knowledgeable as the rest that post to your site,  However I am having
Problems and have tried to post my questions in a most respectful way.

You said to
enable lua errors  and I do have latest version     now sure How to   enable lua errors  but I guess I will google it.    Guess I don’t belong on this website
because Im not as knowledgeable in this type of thing…….but then again not many of these people can build a kick ass gaming rig like I can.

Thank you again,   I will not bother you again ☹


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
