### ISSUE TITLE
Allow Bag break to only break reagent.

### ISSUE THREAD

**Issue by githubcmass** [Jaliborc/Bagnon#1555]
Hello there,

the default UI allows the bag to only break the reagent back. 

Could we have this done please ?

**Comment by ChloeMarie** [comment]
Please!

**Comment by IndigoRandom** [comment]
Hi! I've made a set of changes for this [here](https://github.com/Jaliborc/Wildpants/pull/93)  (fair warning: I'm not Jaliborc and these changes are definitely not official in any way, shape or form). If you update the Wildpants folder in `Interface/Addons/Bagnon/common/Wildpants`, then it should work. Also, the option only works in English otherwise you'll get a mystery box on the config. Sorry about that bit!
