### ISSUE TITLE
Bagnon Version 10.0.11: `UseContainerItem()` taint prevents users from interacting with items in their inventory.

### ISSUE THREAD

**Issue by Ghostamoose** [Jaliborc/Bagnon#1579]
This is a known [UI Bug](https://github.com/Stanzilla/WoWUIBugs/issues/310).

There's a workaround mentioned in the thread above, but it's incredibly cumbersome. You can easily reproduce this error with no addons enabled by using `/run OpenAllBags()` then attempting to use an item in your bag.

The only fix for this bug right now is to revert to Bagnon version 10.0.10 until it's updated.

**Comment by Fleymour** [comment]
ye  since last night i cant use the items anymore in my bags:

2x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
[string "=[C]"]: ?

**Comment by zdhar** [comment]
its not bagnon himself but bagnon item level

**Comment by l0bster** [comment]
Getting this error even with Bagnon_ItemLevel Plugin disabled:

> 4x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
[string "=[C]"]: ?

**Comment by Ghostamoose** [comment]
Appears to be fixed in version 10.0.12 - thanks @Jaliborc. I'm looking into this specific taint issue more closely and can update you  when I find something if you'd like. 👍 

(although it would be great if Blizzard fixed this bug themselves)
