### ISSUE TITLE
I'd like to be able to drag my item bag and leave it anywhere on the screen.  Is that possible?

### ISSUE THREAD

**Issue by plokert** [Jaliborc/Bagnon#1665]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZForceSeattle** [comment]
I hope this is an acceptable thing to say. I use BlizzMove with Bagnon and all my other add-ons, which works beautifully. Since putting the two together in Shadowlands I have had no problem. 

Of course, that is always a period after a major update when Blizzard breaks everything, like this past week, but within the week and sometimes within hours, the addon writers fix everything, and everything becomes perfect again. I almost went nuts this week after Blizzard kept disabling Bagnon on me. 

I hope this helps you with your answer.  Personally, let each programmer do what they need to do and complement each other.

**Comment by plokert** [comment]
Thankyou ZForceSeattle,  I looked into a work around for the issue and found Blizzmove works just fine.  :)
